### ISSUE TITLE
Configure with pyproject.toml

### ISSUE THREAD

**Issue by catcombo** [asottile/add-trailing-comma#171]
First of all, I want to say thank you for `add-trailing-comma`. It's a very good addition to `black` and `isort` and eliminates the need to think about the code style.

The only inconvenience is the lack of a configuration file. In some projects we have files or even directories we want to exclude from `add-trailing-comma`. We have to use custom scopes for watcher tasks in PyCharm and filter files in GitHub CI actions for `add-trailing-comma`. In the same time, `black` and `isort` can be easily configured via `pyproject.toml`.

I'm wondering do you have plans to implement this feature and how can I help with it?

**Comment by asottile** [comment]
there's no options so no need for configuration -- also if you're using black you shouldn't use add-trailing-comma

**Comment by zyv** [comment]
@asottile, could you please explain why shouldn't we be using `add-trailing-comma` if we are using `black`? It doesn't insert trailing commas on its own, as far as I'm aware.

Regarding the lack of options to configure, @catcombo actually was asking to add one to exclude files, maybe the issue should have been named better to make this more obvious.

**Comment by asottile** [comment]
- `black` and `add-trailing-comma` disagree on some formatting
- there's no need to implement "exclude" because add-trailing-comma (**intentionally**) does not do recursion, only taking positional argument filenames.  if you want exclusion I'd recommend you use pre-commit's [exclude](https://pre-commit.com/#top_level-exclude) -- or compose unix commands `git ls-files -- '*.py' | grep -v ... | xargs add-trailing-comma` or some such
