### ISSUE TITLE
autopep8 conflict with multi-line context manager

### ISSUE THREAD

**Issue by chriskuehl** [asottile/add-trailing-comma#36]
## what add-trailing-comma wants
```python
def a():
    with b(c), \
        d(
            e,
        ):
        pass
```

## what autopep8 wants
```python
def a():
    with b(c), \
        d(
            e,
    ):
        pass
```

gross :(

**Comment by asottile** [comment]
This problem is rooted in `pycodestyle`:

```
test.py:6:5: E125 continuation line with same indent as next logical line
```

honestly there's no "nice" formatting of these continued `with` statements that appeases both tools :/

I don't think there's anything that can be done here from the add-trailing-comma side -- the code probably just needs to have manual human rewriting:

### two withs

```python
with b(c):
    with d(e):
        # ...
```

### not-so-great implicit continuation
```python
with b(
    c,
), d(
    e,
):
    # ...
```

I really just wish python let you do something like

```python
with (
    b(c),
    d(e),
):
```

**Comment by asottile** [comment]
Since I don't think there's anything actionable here (other than for the human to pick a different syntax approach that isn't ugly) I'm going to close this.  It's good documentation for resolving these conflicts manually though so I'm going to keep documenting these and tagging them with [autopep8]

**Comment by qudade** [comment]
Here an alternative that makes autopep8 *and* add-trailing-comma happy:

```
def a():
    with b(c), d(e,):
        pass
```
